/* Automatically generated by './build/bin/build-entry.js' */
import MessageBox from '../components/message-box/index.js'
import Alert from '../components/alert/index.js'
import Notification from '../components/notification/index.js'
import Loading from '../components/loading/index.js'
import Message from '../components/message/index.js'
import InfiniteScroll from '../components/infinite-scroll/index.js'

import locale from './locale/index.js'

const components = [
  MessageBox,
  Alert,
  Notification,
  Message,
  InfiniteScroll
]

const install = function (Vue, opts = {}) {
  locale.use(opts.lang)
  locale.i18n(opts.i18n)

  components.forEach(component => {
    console.log(component.name)
    Vue.component(component.name, component)
  })

  Vue.use(InfiniteScroll)
  Vue.use(Loading.directive)

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  }

  Vue.prototype.$loading = Loading.service
  Vue.prototype.$msgbox = MessageBox
  Vue.prototype.$alert = MessageBox.alert
  Vue.prototype.$confirm = MessageBox.confirm
  Vue.prototype.$prompt = MessageBox.prompt
  Vue.prototype.$notify = Notification
  Vue.prototype.$message = Message
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '1.0.0',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  MessageBox,
  Alert,
  Notification,
  Loading,
  Message,
  InfiniteScroll
}
